### ISSUE TITLE
Error on Spigot 1.9

### ISSUE THREAD

**Issue by Nomy** [nitnelave/CreeperHeal#30]
`[05:05:29] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CreeperHeal v6.8.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-1a196e1-6f032cd]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1a196e1-6f032cd]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:840) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_71]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_71]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-1a196e1-6f032cd]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
    at com.nitnelave.CreeperHeal.listeners.GriefListener.onPlayerInteract(GriefListener.java:179) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-1a196e1-6f032cd]
    ... 17 more`

**Comment by nitnelave** [comment]
I don't really have time to fix that right now... But as a workaround, give everyone the permission "bypass.spawnEgg", and that shouldn't happen anymore.
