### ISSUE TITLE
Error when hit by monster

### ISSUE THREAD

**Issue by xickle** [nitnelave/CreeperHeal#43]
```
[12:29:59] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CreeperHeal v7.0.4
org.bukkit.event.EventException
   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:92) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:577) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:482) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:609) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1309) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:864) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:855) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityEnderDragon.b(EntityEnderDragon.java:396) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityEnderDragon.n(EntityEnderDragon.java:258) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.entity.CraftEnderDragon cannot be cast to org.bukkit.entity.Player
   at com.nitnelave.CreeperHeal.listeners.GriefListener.onEntityDamageByEntity(GriefListener.java:114) ~[?:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
   ... 25 more
```
Running Spigot 1.11 and CreeperHeal 7.0.4.

Error happens every time a monster hits a player on the server. It also happened in older versions of CreeperHeal(7.0.2)

**Comment by nitnelave** [comment]
Fixed in 7.0.5.
